# Generated by Django 4.1.2 on 2022-11-27 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_phone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
