# Generated by Django 4.1.2 on 2022-11-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_slot_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot_booking',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
