# Generated by Django 4.1.2 on 2023-01-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='comment',
            field=models.TextField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
